### ISSUE TITLE
Not able to create buckets

### ISSUE THREAD

**Issue by sherbertiConstruct** [Developer-Autodesk/view.and.data-dotnet-wpf.tutorial#1]
Hello 

I am having a problem creating buckets through the UI. I keep getting the error Bucket creation failed: 0. It doesn't seem to matter what I put into the bucket creation. 

I have logged in successfully but I don't seem to be able to get any further. 

Any idea what would cause this error? 

Thanks

**Comment by leefsmp** [comment]
Are you sure you correctly placed your API credentials in the Credentials.cs file? The bucket name should not contain special characters and needs to be lower case, also it has to be unique service-wide, so basic names such as "bucket1" have probably been taken by somebody else

**Comment by sherbertiConstruct** [comment]
I used the bucket name "iconstruct12072016073041" and I did update the credentials.cs file with my correct credentials. I checked my credentials against the website "https://tranquil-thicket-28252.herokuapp.com/"

**Comment by leefsmp** [comment]
Ha if you requested the credentials recently, you need to specifiy scope "bucket:create" the sample has not been migrated to include scope in the token request. 

See that [thread](http://forums.autodesk.com/t5/view-and-data-api/403-forbidden/td-p/6424679) for more details

**Comment by sherbertiConstruct** [comment]
Thank you 

I added this line to the source code and I can create a bucket. 
 request.AddParameter("scope", "bucket:create");

How could I add data:read, data:write to the scope as well? 

request.AddParameter("scope", "bucket:create, data:read, data:write");

The above line does not work could you suggest a better way to do that?

**Comment by leefsmp** [comment]
It has to be a space-separated, url encoded string, I'm not sure if request will url encode the parameter for you: "scope=bucket:create bucket:read data:write" (or the url-encoded version "scope=bucket:create%20bucket:read%20data:write")

See there for more details:
[http://adndevblog.typepad.com/cloud_and_mobile/2016/07/setting-the-scope-for-the-token.html](http://adndevblog.typepad.com/cloud_and_mobile/2016/07/setting-the-scope-for-the-token.html)

**Comment by sherbertiConstruct** [comment]
Both of the "scope=bucket:create bucket:read data:write"  and "scope=bucket:create%20bucket:read%20data:write" cause the same error Authentication failed:

**Comment by leefsmp** [comment]
Can you show the exact code you are running? because the following definitely works fine on my side... 

    private Task<TokenResponse> GetAccessTokenAsync() {

        var request = new RestRequest(
            "authentication/v1/authenticate", 
            Method.POST);

        request.AddParameter("client_id", _clientKey);
        request.AddParameter("client_secret", _secretKey);
        request.AddParameter("grant_type", "client_credentials");
        **request.AddParameter("scope", "data:read data:create data:write bucket:read bucket:create");**

        return _restClient.ExecuteAsync
            <TokenResponse>(request);
    }

**Comment by sherbertiConstruct** [comment]
I must have had something wrong in the sequence of my add parameter because your code works great. 

Thank you for your help.

**Comment by leefsmp** [comment]
Welcome ;)
